package com.zy.ppmusic.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zy.ppmusic.entity.MusicDbEntity;

import com.zy.ppmusic.data.db.dao.MusicDbEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicDbEntityDaoConfig;

    private final MusicDbEntityDao musicDbEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicDbEntityDaoConfig = daoConfigMap.get(MusicDbEntityDao.class).clone();
        musicDbEntityDaoConfig.initIdentityScope(type);

        musicDbEntityDao = new MusicDbEntityDao(musicDbEntityDaoConfig, this);

        registerDao(MusicDbEntity.class, musicDbEntityDao);
    }
    
    public void clear() {
        musicDbEntityDaoConfig.clearIdentityScope();
    }

    public MusicDbEntityDao getMusicDbEntityDao() {
        return musicDbEntityDao;
    }

}
